# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-06 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u9879\u76ee\u7f16\u53f7')),
                ('name', models.CharField(max_length=200, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('status', models.CharField(default='stop', editable=False, max_length=200, verbose_name='\u9879\u76ee\u72b6\u6001')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='\u9996\u6b21\u521b\u5efa\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u666f\u533a')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u6570\u636e\u7c7b\u578b')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u7f51\u7ad9\u6765\u6e90')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Region'),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Type'),
        ),
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Website'),
        ),
    ]
